apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-sre
spec:
  schedule: "{{ .Values.cronJob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: "{{ .Values.cronJob.image.repository }}:{{ .Values.cronJob.image.tag }}"
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - echo "Hello SRE"
          restartPolicy: {{ .Values.cronJob.restartPolicy }}
