apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloworld
  name: helloworld-svc
spec:
  ports:
  - nodePort: 30134
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: helloworld
  type: NodePort